### ISSUE TITLE
Cool concept but doesn't really work.

### ISSUE THREAD

**Issue by enricribas** [pusher/atom-pair#17]
Is the intention that we can only share one file? If one person open another file, is it supposed to open for  that person? 

Also the bar "your buddy has joined" covers the file tabs.

I disconnect, and then try to start a new session and it says "It looks like you're already in a pairing session..." No.?

ok, start over. I open Gemfile on the right. Start new session... Join the session from the left. I can an untitled window? Shouldn't I see Gemfile? Ok, I'll open Gemfile from the left... It doesn't open. ?  Should I open the file first and then join a session? 

Maybe it doesn't work on the same computer. I get a friend to try. Blank untitled screen seems to work, but with an existing file open, doesn't seem to share, even if I cancel everything open the file and then start session. He sees nothing change, plus he had to manually open a page because he got a blank untitled one even though I was on Gemfile. Also if I open a file, should he see it open or do I have to start another session for that file?

Sorry, I really want this work because I work remotely but I don't get it.

**Comment by edersonbadeca** [comment]
:+1:

**Comment by giefferre** [comment]
I partially agree.

The feature I miss above all is the possibility to share an entire working directory, not a single file.

**Comment by jpatel531** [comment]
Thanks for the feedback! I'll get on it when I have some time, for sure. 

I recently added the "It looks like you're already in a pairing session..." alert to 'force' people to open a new Atom window as some users were getting issues with the cleanup. But admittedly it is a bit of a hack that I can amend.

@enricribas - what happens when you have an already open file, and start a new pairing session with that as the active tab? Does your friend not see it appear when he joins the session? 

I'll definitely put the option to open a new file in a session, and to share a directory on the todos, for sure

**Comment by kevinsimper** [comment]
@jpatel531 When i pair with another person and I already have a active tab, that files is shown on the other persons computer as `untitled`. Is that the same issue, or should I create a new one?

**Comment by jpatel531** [comment]
When I merge and release #68 - this will be solved. Hopefully I can do this within the next few days
